version: '3.5'

services:
  node:
    image: node:13
    container_name: facebook-login
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    working_dir: /app
    command: tail -f /dev/null
    networks:
      - symfony-api-platform-network

networks:
  symfony-api-platform-network:
    external: true
