App\Entity\User:
  attributes:
    id:
      groups: [ user_read ]
    name:
      groups: [ user_read, user_register, user_update ]
    email:
      groups: [ user_read, user_register ]
    password:
      groups: [ user_register ]
    avatar:
      groups: [ user_read ]
    active:
      groups: [ user_read ]
    token:
      groups: [ user_activate ]
    createdAt:
      groups: [ user_read ]
    updatedAt:
      groups: [ user_read ]
    groups:
      groups: [ user_read ]
    movements:
      groups: [ user_read ]
